const diTokens = {
    //PRODUCTS_MONGO_DAO_TOKEN: 'PRODUCTS_MONGO_DAO_TOKEN',
  
    PRODUCTS_BO_TOKEN: 'PRODUCTS_BO_TOKEN',
    
    AUTH_CONTROLLER_TOKEN: 'AUTH_CONTROLLER_TOKEN',
    USERS_BO_TOKEN: 'USERS_BO_TOKEN',

}
export default diTokens